### ISSUE TITLE
Table Change Function for Users

### ISSUE THREAD

**Issue by LFPower** [Breakthrough-Energy/PreREISE#160]
It is more reasonable for users to change table by using plant name, branch name, substation name.  It is suggested that add new columns for plant.csv, branch.csv, substation.csv.
For plant.csv:  plant name, city, county, state, zip code, owner
For branch.csv: branch name, start substation, end substation, start city, end city, start county, end county, start state, end state, owner .
For substaion.csv, substation name, city, county, state, zip code, owner.

**Comment by danielolsen** [comment]
I see at least two distinct tasks that would be required for this:
1. Add name/owner to plants, name/owner to branches, and name/owner/city/county/state/zip to substations (since we can pull the extra locational data for the plants/branches from the associated substations).
2. Extend the functionality of the ChangeTable methods to be able to specify names for scaling, rather than IDs.

For (1), we would need to make the change to the existing `usa_tamu` grid model in PowerSimData, and adjust the generation of the `hifld` model in PreREISE. (2) seems like it would be entirely within PowerSimData.

Expanding the data structure of the Grid object is not something that we do lightly, because until now we have ensured that we can create equivalent data structures from a set of CSVs (a 'base grid'), from transforming a base grid via an arbitrary number of ChangeTable operations, and from reading .mat files that record all grid data as it was sent to the optimization, including any modifications to grid data that are made as part of the simulation process (e.g. linearization of cost curves, relaxation of minimum generation, etc.). The last case is the most challenging to deal with. Since the 'base grid' data is subject to change, any data that we want to have available when we load a Grid from a .mat file must be contained in that file. Internally, we have several thousand of these files on our server already, so in order to be able to get the same names for the same elements via all methods we would need to add the new information to all of our previous grid records, which must be done semi-manually.

**Comment by danielolsen** [comment]
Thinking about this a bit more, it seems that when we load a Grid from CSVs, we by default load all available columns. Then, when preparing the data to be run, we drop specific columns that aren't needed by the simulation engine. If instead, we only _kept_ specific columns that are needed by the simulation engine, then we could have all of the additional information in the CSVs, which would get loaded into a Grid object and be available to the user for them to query to do filtering by name, owner, etc, and then pass that information to the appropriate change table methods.

It would mean that there _could_ be different sets of columns available within a Grid object for a) grids loaded from matfiles, b) a `usa_tamu` grid, and c) an `hifld` grid. Currently, (a) and (b) are the same, but we could add additional information to the `usa_tamu` CSVs such that all of (a), (b), and (c) would be different. If we wanted, we could also try to load the additional column information from CSVs when we load matfiles, by looking up via indexes, but that would only work for existing scaled entries, not for new entries.

**Comment by danielolsen** [comment]
Closed in favor of more specific issues in each repo:
- https://github.com/Breakthrough-Energy/PreREISE/issues/242
- https://github.com/Breakthrough-Energy/PowerSimData/issues/567
